### ISSUE TITLE
 Чо удалил-то?

### ISSUE THREAD

**Issue by oxxxxxy** [Voiislav/mesto#1]
Тебе ответили по тестовому вообще? Мне вообще по нулям.

**Comment by Voiislav** [comment]
> Тебе ответили по тестовому вообще? Мне вообще по нулям.

нет, ответа не было, мне эта репа не нужна )

**Comment by oxxxxxy** [comment]
Пон, давай тогда, удачи тебе в АйТи. Всё будет збс. :+1:

**Comment by Voiislav** [comment]
> Пон, давай тогда, удачи тебе в АйТи. Всё будет збс. 👍

спасибо, и тебе )
